### ISSUE TITLE
HELP-415 GlyTouCan IDs masterlist to PubChem mapping URL

### ISSUE THREAD

**Issue by jeremywalter** [nih-cfde/helpdesk-collaboration#4]
As discussed the GlyTouCan IDs masterlist to PubChem mapping is now available from a stable URL on [data.glygen.org](http://data.glygen.org/) - https://data.glygen.org/ln2data/releases/data/current/reviewed/glycan_pubchem_status.csv. Sorry it took long because our new drosophila data was not ready.   

The file gets updated with the GlyGen release, which is mostly and usually quarterly (sometimes it may take longer), so you can fetch it often, or we can let you know when to update. The URL won't change even if the file is updated next time. We will also be implementing automatic update notifications, but it will take some time to implement.   

Can you update the script/files at your end to reflect the new glycans in the list.  
Let me know if you have any questions. Thanks

**Comment by jonathancrabtree** [comment]
Hi @ReneRanzinger, it's possible that Arthur incorporated/updated this mapping before he left, but this Helpdesk issue is one he didn't mention, so I'll have to check on that.

**Comment by jonathancrabtree** [comment]
After reviewing the code and the current state of the published PubChem substance and compound files, it appears that:

1. The last version of the GlyTouCan mapping incorporated (by Arthur) was a file called gtc_pubchem_xref_status.csv, with 33756 lines (including header) and an MD5 checksum of b6e820ac60c0ba0b2633cbb1a58938a8.
2. The new/current version of the mapping file (downloaded on 1/25/2023 from the URL indicated above) has 34657 lines and  anMD5 checksum of c4d70c14688f72ffcbb33b998d6f3b71.
3. The format of the new file is slightly different and Arthur's pipeline/scripts will have to be updated accordingly. The differences I see are:
   - All fields in the new file are quoted.
   - The 2nd column is now "pubchem_xref_exists" instead of "status", though the information encoded is the same.
   - The old file always had compound before substance (in fields 3 and 4), the new one does not.

We'll have to update the processing pipeline code and then run it to incorporate the new mapping. I don't have a timeline for this yet, but it will be before the next submission window opens.

**Comment by jonathancrabtree** [comment]
Scripts have been modified to accept the new GlyTouCan file format and GlyTouCan processing is complete. Currently waiting for PubChem processing to complete so that the new terms can be merged in.

**Comment by jonathancrabtree** [comment]
Terms merged, updating compound.tsv.gz and substance.tsv.gz files on OSF.io

**Comment by jonathancrabtree** [comment]
New compound.tsv.gz and substance.tsv.gz files are available on [https://osf.io/bq6k9/](https://osf.io/bq6k9/) and were announced in a recent e-mail to all submitter.s
